AWSTemplateFormatVersion: 2010-09-09

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

Outputs:
  Name:
    Value: !Ref Bucket
  Arn:
    Value: !GetAtt Bucket.Arn